version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    # 필요시 volumes, restart 정책 추가 가능

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - auth-db
    # 필요시 volumes, restart 정책 추가 가능

  event:
    build:
      context: ./event
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - event-db
    # 필요시 volumes, restart 정책 추가 가능

  auth-db:
    image: mongo:6.0
    container_name: auth-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: admin
      MONGODB_DATABASE: user
      MONGODB_PASS: auth_admin_password
    volumes:
      - mongo-data:/data/auth-db

  event-db:
    image: mongo:6.0
    container_name: event-db
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGODB_USER: admin
      MONGODB_DATABASE: user
      MONGODB_PASS: event_admin_password
    volumes:
      - mongo-data:/data/event-db

volumes:
  mongo-data:

